### ISSUE TITLE
구조

### ISSUE THREAD

**Issue by ag502** [woowa-techcamp-2021/store-9#13]
## :hammer: 기능 설명

기능 설명
프론트엔트 구조

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 프론트엔드 폴더 구조
- [x] webpack
- [x] babel
- [x] eslint
- [x] prettier

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

**Comment by crongro** [comment]
예) 
  작업크기 : 2MD
