### ISSUE TITLE
9팀 페어 코드 리뷰~~

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/store-9#50]
## :hammer: 기능 설명

기능 설명

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by Kyun2da** [comment]
저는 댓글로 남긴게 없어서 인상적이었던거 적어보려고 합니다~

- 리액트 훅스에 대한 lint를 적용했던 것이 너무 좋았습니다. 저희 팀에도 적용해보자고 제안을 나중에 드려봐야 겠어요!
- 스웨거를 사용하신다는 것에서 놀랐습니다! 저희도 api 문서 정의서 같은거 하나 있으면 좋겠다는 생각을 했어요
- 타입스크립트 제네릭을 쓰셨던데 저는 아직 제네릭을 잘 다루지 못해서 그러한 것을 잘 쓰시는 모습이 되게 인상적이었습니다!
- 컴포넌트 폴더에서 1depth 더 나누신것도 인상적이었습니다. 저희는 아직 component폴더 하나에 다 넣고 있는데 이부분도 나중에 저희팀에 적용해보면 좋겠다는 생각을 했습니다.

배울게 많은 시간이었습니다! 9팀 남은 기간 화이팅 하시길 바랍니다 👍 😄

**Comment by HanCheo** [comment]
#34
#21
#19
#31

아휴 엔티티 모델링 하신거 잘 봣습니다
거진 잡담인데....;;; 잘 보구 갑니다~ !

**Comment by KangyeolLee** [comment]
와우 리뷰를 굉장히 꼼꼼하게 잘 하시네요~~ 잘 보고 갑니다 :)
궁금한걸 바로바로 슬랙에서 여쭤봐서 중복되는 건 지우고 답니다~~ (그러니깐 하나 밖에 없네요?!)

#21

**Comment by dongqui** [comment]
- 팀 분위기가 인상적이었어요! 리뷰가 굉장히 활발해 보이네요!
- 컴포넌트 폴더 뎁스가 인상적이었습니다! 저희도 벌써 엄청 늘어났는데, 참고 하겠습니다 😄 
- 스웨거 기대중이에요..ㅋㅋㅋ

**Comment by dongqui** [comment]
+ 혁주님 아토믹은요....?

**Comment by Hyoukjoo** [comment]
> +혁주님 아토믹은요....?

그게 머죠...? ㅋㅋㅋ
